import type { Metadata } from "next";
import "../styles/globals.css";
import DashboardLayout from "@/components/DashboardLayout";
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DashboardLayout>
          {children}
        </DashboardLayout>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
